using System.Collections.Generic;
using HarmonyLib;
using RimWorld;
using Verse;

namespace GITM
{
    [HarmonyPatch(typeof(RaceProperties), nameof(RaceProperties.SpecialDisplayStats))]
    public static class Patch_RaceProperties_SpecialDisplayStats
    {
        // By taking IEnumerable<StatDrawEntry> as the first parameter and returning one,
        // Harmony automatically pipes the vanilla output through this method.
        public static IEnumerable<StatDrawEntry> Postfix(IEnumerable<StatDrawEntry> values, ThingDef parentDef, StatRequest req)
        {
            // Iterate through the vanilla entries generated by the original method
            foreach (StatDrawEntry entry in values)
            {
                // Identify the hardcoded "MechWorkSkill" entry. 
                // Vanilla uses display priority 501 for this specific entry.
                if (entry.category == StatCategoryDefOf.PawnWork && entry.DisplayPriorityWithinCategory == 501)
                {
                    // Check if the info card is for a specific instantiated pawn, rather than a generic recipe
                    if (req.HasThing && req.Thing is Pawn pawn)
                    {
                        CompMechSkillMemory comp = pawn.TryGetComp<CompMechSkillMemory>();
                        if (comp != null)
                        {
                            yield return new StatDrawEntry(
                                StatCategoryDefOf.PawnWork,
                                "MechWorkSkill".Translate(),
                                "Brainscan Override",
                                "This mechanoid does not use a fixed skill level. Its skills are inherited from its scanned human template. Check the pawn's Skills tab for exact values.",
                                501);

                            continue; // Skip yielding the vanilla '10' entry
                        }
                    }
                    else if (!req.HasThing && parentDef.HasComp(typeof(CompMechSkillMemory)))
                    {
                        yield return new StatDrawEntry(
                            StatCategoryDefOf.PawnWork,
                            "MechWorkSkill".Translate(),
                            "Varies (Scanned)",
                            "This mechanoid type inherits skills from a human brainscan.",
                            501);

                        continue;
                    }
                }

                // If it's not the entry we want to replace, or not our mech, just pass the vanilla entry through untouched
                yield return entry;
            }
        }
    }
}